name: flutter_vlc_player_workspace     # Can be anything

environment:
  sdk: ^3.6.0

publish_to: none

workspace:
  - flutter_vlc_player
  - flutter_vlc_player/example
  - flutter_vlc_player_platform_interface
  - flutter_vlc_player_android
  - flutter_vlc_player_ios