name: flutter_vlc_player_android
description: "Android implementation of flutter_vlc_player."
version: 1.0.0
repository: https://github.com/solid-software/flutter_vlc_player/flutter_vlc_player_android
issue_tracker: https://github.com/solid-software/flutter_vlc_player/issues

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

resolution: workspace

flutter:
  plugin:
    implements: flutter_vlc_player
    platforms:
      android:
        package: software.solid.fluttervlcplayer
        pluginClass: FlutterVlcPlayerPlugin
        dartPluginClass: AndroidFlutterVlcPlayer

dependencies:
  flutter:
    sdk: flutter
  flutter_vlc_player_platform_interface: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^25.2.0
  solid_lints: ^0.3.0
